/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoologico.tarea2;

import zoologico.tarea2.PanelesModificar.Mmamiferos;
import zoologico.tarea2.PanelesModificar.Martropodos;
import zoologico.tarea2.PanelesModificar.Mequinodermos;
import zoologico.tarea2.PanelesModificar.Mpeces;
import zoologico.tarea2.PanelesModificar.Mgusanos;
import zoologico.tarea2.PanelesModificar.Mcelentereos;
import zoologico.tarea2.PanelesModificar.Mmoluscos;
import zoologico.tarea2.PanelesModificar.Manfibios;
import zoologico.tarea2.PanelesModificar.Maves;
import zoologico.tarea2.PanelesModificar.Mreptiles;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author Wilson
 */
public class Modificar extends javax.swing.JFrame {
    public String usuario;
    public String contrasena;
    private Mmamiferos MMamiferos;
    private Maves Maves;
    private Mpeces Mpeces;
    private Mreptiles Mreptiles;
    private Manfibios Manfibios;
    private Martropodos Martropodos;
    private Mmoluscos Mmoluscos;
    private Mequinodermos Mequinodermos;
    private Mcelentereos Mcelentereos;
    private Mgusanos Mgusanos;

    /**
     * Creates new form Modificar
     * @param usuario
     * @param contrasena
     */
    public Modificar(String usuario,String contrasena) {
        initComponents();
        this.usuario=usuario;
        this.contrasena=contrasena;
            
    }
    private void mostrarPanel(JPanel p){
        p.setSize(296,327);
        p.setLocation(0,0);
        
        jPanel1.removeAll();
        jPanel1.add(p,BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okBoton = new javax.swing.JButton();
        grupo = new javax.swing.JComboBox<>();
        bModificar = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        mnombre = new javax.swing.JTextField();
        mpeso = new javax.swing.JTextField();
        mcolor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 255, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        okBoton.setText("OK");
        okBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotonActionPerformed(evt);
            }
        });

        grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamiferos", "Aves", "Reptiles", "Anfibios", "Peces", "Antropodos", "Moluscos", "Equinodermos", "Gusanos", "Poriferos", "Celentereos" }));
        grupo.setToolTipText("");
        grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar>>");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        mpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpesoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Peso");

        jLabel4.setText("Color");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 255));
        jLabel5.setText("Modificar animales");

        volver.setText("<<Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volver)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mpeso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mcolor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(okBoton))
                                .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(bModificar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okBoton)
                            .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bModificar)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(mpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(volver)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoActionPerformed

    private void okBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotonActionPerformed
        switch (grupo.getSelectedItem().toString()) {
                case "Mamiferos":
                    MMamiferos= new Mmamiferos();
                    mostrarPanel(MMamiferos);
                    break;
                case "Aves":
                    Maves=new Maves();
                    mostrarPanel(Maves);
                    break;
                case "Peces":
                    Mpeces=new Mpeces();
                    mostrarPanel(Mpeces);
                    break;
                case "Reptiles":
                    Mreptiles=new Mreptiles();
                    mostrarPanel(Mreptiles);                 
                    break;
                case "Anfibios":
                    Manfibios=new Manfibios();
                    mostrarPanel(Manfibios);  
                    break;

                case "Antropodos":
                    Martropodos=new Martropodos();
                    mostrarPanel(Martropodos);  
                    break;
                case "Moluscos":
                    Mmoluscos=new Mmoluscos();
                    mostrarPanel(Mmoluscos);  
                    break;
                case "Celentereos":
                    Mcelentereos= new Mcelentereos();
                    mostrarPanel(Mcelentereos);
                    break;
                case "Gusanos":
                    Mgusanos= new Mgusanos();
                    mostrarPanel(Mgusanos);
                    break;
                case "Equinodermos":
                    Mequinodermos= new Mequinodermos();
                    mostrarPanel(Mequinodermos);
                    break;
                }
    }//GEN-LAST:event_okBotonActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        try (Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/zoobd", usuario, contrasena)) {
            
       
            String set ="nombre='"+mnombre.getText()+"',peso="+mpeso.getText()+",color='"+mcolor.getText()+"'";
            switch (grupo.getSelectedItem().toString()) {
                case "Mamiferos":
                    set +=",n_patas="+MMamiferos.datoEspecial.getText();
                    break;
                case "Aves":
                    set +=",n_alas="+Maves.datoEspecial.getText();
                    break;
                case "Peces":
                    set +=",c_aletas="+Mpeces.datoEspecial.getText()+",escamas="+Mpeces.datoEspecialDos.getSelectedItem().toString();
                    break;
                case "Reptiles":
                    set +=",tipo="+"'"+Mreptiles.datoEspecial.getSelectedItem().toString()+"'";
                    break;
                case "Anfibios":
                    set +=",piel="+Manfibios.datoEspecial.getSelectedItem().toString();
                    break;
                case "Antropodos":
                    set +=",c_pares_patas="+Martropodos.datoEspecial.getText()+",antenas="+Martropodos.datoEspecialDos.getSelectedItem().toString();
                    break;
                case "Moluscos":
                    set +=",t_concha="+Mmoluscos.datoEspecial.getText();
                    break;
                case "Celentereos":
                    set +=",tentaculos="+Mcelentereos.datoEspecial.getSelectedItem().toString();
                    break;
                case "Gusanos":
                    set +=",cuerpo="+Mgusanos.datoEspecial.getText();
                    break;
                case "Equinodermos":
                    set +=",tipo="+Mequinodermos.datoEspecial.getSelectedItem().toString();
                    break;
                }
            System.out.println(set);
            PreparedStatement ps = c.prepareStatement("UPDATE "+grupo.getSelectedItem().toString()+" set "+set+" WHERE id="+ID.getText()+";");
            ps.execute();
            c.close();
        }
        catch (SQLException ex) {
            System.out.println("ERROR  "+ex);
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void mpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpesoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new ZoologicoGui(usuario,contrasena).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mcolor;
    private javax.swing.JTextField mnombre;
    private javax.swing.JTextField mpeso;
    private javax.swing.JButton okBoton;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
