/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoologico.tarea2;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author Wilson
 */
public class Modificar extends javax.swing.JFrame {
    public String usuario;
    public String contrasena;
    private Mmamiferos MMamiferos;
    private Maves Maves;

    /**
     * Creates new form Modificar
     * @param usuario
     * @param contrasena
     */
    public Modificar(String usuario,String contrasena) {
        initComponents();
        this.usuario=usuario;
        this.contrasena=contrasena;
            
    }
    private void mostrarPanel(JPanel p){
        p.setSize(296,327);
        p.setLocation(0,0);
        
        jPanel1.removeAll();
        jPanel1.add(p,BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okBoton = new javax.swing.JButton();
        grupo = new javax.swing.JComboBox<>();
        bModificar = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        mnombre = new javax.swing.JTextField();
        mpeso = new javax.swing.JTextField();
        mcolor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        okBoton.setText("OK");
        okBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotonActionPerformed(evt);
            }
        });

        grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamiferos", "Aves", "Reptiles", "Anfibios", "Peces", "Antropodos", "Moluscos", "Equinodermos", "Gusanos", "Poriferos", "Celentereos" }));
        grupo.setToolTipText("");
        grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar>>");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        mpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpesoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Peso");

        jLabel4.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mpeso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mcolor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(okBoton))
                                .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(295, 295, 295)
                        .addComponent(bModificar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okBoton)
                            .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(mpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoActionPerformed

    private void okBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotonActionPerformed
        switch (grupo.getSelectedItem().toString()) {
                case "Mamiferos":
                    MMamiferos= new Mmamiferos();
                    mostrarPanel(MMamiferos);
                    break;
                case "Aves":
                    Maves=new Maves();
                    mostrarPanel(Maves);
                    break;
//                case "Peces":
//                    
//                    break;
//                case "Reptiles":
//                    
//                    
//                    break;
//                case "Anfibios":
//                    
//                    break;
//                case "Antropodos":
//                    
//                    break;
//                case "Moluscos":
//                   
//                    break;
//                case "Celentereos":
//                    
//                    break;
//                case "Gusanos":
//                    
//                    break;
//                case "Equinodermos":
//                    
//                    break;
                }
    }//GEN-LAST:event_okBotonActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        try (Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/zoobd", usuario, contrasena)) {
            
       
            String set ="nombre='"+mnombre.getText()+"',peso="+mpeso.getText()+",color='"+mcolor.getText()+"'";
            switch (grupo.getSelectedItem().toString()) {
                case "Mamiferos":
                    set +=",n_patas="+MMamiferos.datoEspecial.getText();
                    break;
                case "Aves":
                    set +=",n_alas="+Maves.datoEspecial.getText();
                    break;
                case "Peces":
                    set +=",n_alas="+Mpeces.datoEspecial.getText();
                    break;
                case "Reptiles":
                    set +=",n_alas="+Mrepitles.datoEspecial.getText();
                    break;
                case "Anfibios":
                    set +=",n_alas="+Manfibios.datoEspecial.getText();
                    break;
//                case "Antropodos":
//                    parametros+=",c_pares_patas,antenas";
//                    valores +=",'"+cAntropodos.patasAntropodos.getText()+"','"+cAntropodos.antenas.getSelectedItem()+"'";
//                    break;
//                case "Moluscos":
//                    parametros+=",t_concha";
//                    valores +=","+cMoluscos.concha.getText();
//                    break;
//                case "Celentereos":
//                    parametros+=",tentaculos";
//                    valores +=",'"+cCelentereos.tentaculos.getText()+"'";
//                    break;
//                case "Gusanos":
//                    parametros+=",cuerpo";
//                    valores +=",'"+cGusanos.cuerpoGusano.getText()+"'";
//                    break;
//                case "Equinodermos":
//                    parametros+=",tipo";
//                    valores +=","+cEquinodermos.tipo.getSelectedItem();
//                    break;
//                default:
//                    parametros = "";
//                    valores = "";
//                    break;
                }
            System.out.println(set);
            PreparedStatement ps = c.prepareStatement("UPDATE "+grupo.getSelectedItem().toString()+" set "+set+" WHERE id="+ID.getText()+";");
            ps.execute();
            c.close();
        }
        catch (SQLException ex) {
            System.out.println("ERROR  "+ex);
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void mpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpesoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mcolor;
    private javax.swing.JTextField mnombre;
    private javax.swing.JTextField mpeso;
    private javax.swing.JButton okBoton;
    // End of variables declaration//GEN-END:variables
}
